example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('details/', show_catalog, name='show_catalog'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from mywatchlist.views import show_html
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_html, name='show_html'),
    path('html/', show_html, name='show_html'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_ajax, name='show_ajax'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', add_activity, name='add_activity'),
    path('delete/<int:id>', delete, name='delete'),
    path('status/<int:id>', status, name='status'),
    path('json/', show_json, name='show_json'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MovieDetails(models.Model):
    watched = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    movie_rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField(max_length=150)

todolist/models.py
from operator import length_hint
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length = 150)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_catalog(request):
    katalogTerdaftar = CatalogItem.objects.all()
    context = {
    'list_barang': katalogTerdaftar,
    'nama': 'Marcelinus Gerardo',
    'npm' : '2106708324'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from urllib import request
from django.shortcuts import render
from mywatchlist.models import MovieDetails
from django.http import HttpResponse
from django.core import serializers


# Create your views here.
def show_html(request):
    data_source = MovieDetails.objects.all()
    context = {
    "movie_details": data_source,
    "nama": "Bobi 88 Gaming",
    "npm": "2106708324",
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MovieDetails.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MovieDetails.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from re import T
from turtle import title
from xmlrpc.client import DateTime
from todolist.models import Task
from django import forms
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.urls import reverse
from django.core import serializers
from django.shortcuts import get_object_or_404

class NewForms(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'size': 37}))
    description = forms.CharField(label="Description", widget=forms.Textarea)

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    details = Task.objects.filter(user=request.user)
    context = {
    'todo_details': details,
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def add_activity(request):
    if request.method == "POST":
        forms = NewForms(request.POST)
        if forms.is_valid():
            new_task = Task(
                user = request.user,
                title = forms.cleaned_data["title"],
                description = forms.cleaned_data["description"],
            )
            new_task.save()
            return redirect("todolist:show_ajax")

    forms = NewForms()
    context={"form":forms}
    return render(request, "addtask.html", context)

# flag
@login_required(login_url='/todolist/login/')
def add_ajax(request):
    if request.method == "POST":
        title=request.POST.get("title")
        description=request.POST.get("description")
        user=request.user
        task = Task(
            title=title,
            description=description,
            user=user,
        )
        task.save()
        return HttpResponse(
            serializers.serialize("json", [task]),
            content_type="application/json",
        )
    return HttpResponse("Invalid method", status_code=405)

@login_required(login_url='/todolist/login/')
def status(request, id):
    # target= get_object_or_404(Task, pk=id)
    target = Task.objects.get(pk=id, user=request.user)
    target.is_finished = not(target.is_finished)
    target.save()
    return redirect("todolist:show_ajax")

@login_required(login_url='/todolist/login/')
def delete(request, id):
    Task.objects.get(id=id, user=request.user).delete()
    return redirect("todolist:show_ajax")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_ajax"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def show_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# ajax function
@login_required(login_url='/todolist/login/')
def show_ajax(request):
    context = {}
    return render(request, "todolist_ajax.html", context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table border="1" bordercolor="rebeccapurple">
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% for i in list_barang %}
      <tr>
        <th>{{i.item_name}}</th>
        <th>{{i.item_price}}</th>
        <th>{{i.item_stock}}</th>
        <th>{{i.description}}</th>
        <th>{{i.rating}}</th>
        <th>{{i.item_url}}</th>
      </tr>
    {% endfor %}
    {% comment %} Add the data below this line {% endcomment %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1 align="center">Assignment 3 PBP/PBD</h1>

  <h5  align="center">Made by: {{nama}} -- {{npm}}</h5>

  <table border="4" bordercolor="rebeccapurple">
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% for i in movie_details %}
      <tr>
        <th>{{i.watched}}</th>
        <th>{{i.title}}</th>
        <th>{{i.movie_rating}}</th>
        <th>{{i.release_date}}</th>
        <th>{{i.review}}</th>
      </tr>
    {% endfor %}
    {% comment %} Add the data below this line {% endcomment %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/addtask.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add Task</title>
<link rel="stylesheet" href="{% static 'todo/style.css' %}">
{% endblock meta %}

{% block content %}

<body> 
  <style>

    .login {
        width: 500px ;
        height: max-content;
        padding: 20px;
        border-radius: 12px;
        background: white;
        box-shadow: 5px 5px #a3a3a3;
    }

    .login form input[type="submit"]{
        font-weight: bold;
        background-color: rgb(4, 113, 214);
        color: azure;
        margin-top: 12px;
    }
  </style>

  <div class="login">
    
    <h1>✒ Add Task</h1>

    <form method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
        <tr>
          <td></td>
          <td><input class="btn" type="submit" name="submit" value="Add" style="float:right"/></td>
        </tr>
      </table>
    </form>

  </div>
</body>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'todo/style.css' %}">
{% endblock meta %}

{% block content %}
<body>

    <div class = "login" style="text-align: center;">
        
        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn btn-success w-100" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     

        Don't have any account? <a href="{% url 'todolist:register' %}">Create account</a>

    </div>

</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Account Registration</title>
<link rel="stylesheet" href="{% static 'todo/style.css' %}">
{% endblock meta %}

{% block content %}  
<body>
    <style>
    
        /* body {
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background-image: linear-gradient(to bottom right, rgb(54, 6, 96), rgb(50, 0, 59));
        }    */
    
        .login {
            width:max-content ;
            height: min-content;
            padding: 20px;
            border-radius: 12px;
            background: white;
            box-shadow: 5px 5px #a3a3a3;
        }

        .login form input[type="submit"]{
            font-weight: bold;
            background-color: rgb(233, 150, 27);
            color: azure;
            margin-top: 12px;
        }
            
    </style>

    <div class = "login">
        
        <h1>Register Now!</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input class="btn" type="submit" name="submit" value="Register" style="float:right"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  
</body>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
 <style>

  .login {
      width: 500px ;
      height: max-content;
      padding: 20px;
      border-radius: 12px;
      background: white;
      box-shadow: 5px 5px #a3a3a3;
  }

  .login form input[type="submit"]{
      font-weight: bold;
      background-color: rgb(9, 210, 106);
      color: azure;
      margin-top: 12px;
  }
</style>

  <h1 style="text-align:center;
  font-family:Cambria">Task Manager</h1>

  <p style="font-size:x-large; text-align: center;
  color: rgb(166, 166, 166)" >Hello, {{ user.get_username }}! Ready for a sunny day? </p>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for i in todo_details %}
      <div class="col">
        <div class="card h-100">
          <div class="card-body d-flex flex-column">
            <h4 class="card-title">{{i.title}} | {% if i.is_finished %}
              ✅
            {% else %}
              ❌
            {% endif %}
            </h4>
            <h6 class="card-subtitle mb-2 text-muted">{{i.date}}</h6>
            <p class="card-text">{{i.description}}</p>
            <div class="flex justify-between gap-3">
              <div class="flex flex-col justify-center rounded">
                <td style="text-align: center"> <button class="btn" style="background-color:rgb(127, 255, 124); border-color:rgb(0, 160, 61); border-width: 2px;">
                  <a href="{% url 'todolist:status' i.id %}">Check </button></td>
                <td style="text-align: center"> <button class="btn" style="background-color:rgb(255, 155, 155); border-color: brown; border-width: 2px;">
                  <a href="{% url 'todolist:delete' i.id %}">Delete </button></td>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <div style="text-align: center">
    <p></p>
    <button class="btn" style="background-color:rgb(219, 237, 255); border-color:blue; border-width: 2px;">
      <a href="{% url 'todolist:add_activity' %}">Add new activity</a></button>
    <button class="btn" style="background-color:rgb(255, 155, 155); border-color: brown; border-width: 2px;">
      <a href="{% url 'todolist:logout' %}">Logout</a></button>

    <p style="color:rgb(166, 166, 166)">Last login: {{ last_login }}</p>
  </div>  


 {% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .show {
        background: rgb(24, 24, 24);
    }
</style>

<body class="show">

    <h1 style="text-align:center;
    font-family:Cambria; color: rgb(255, 255, 255);">Task Manager</h1>

    <p style="font-size:x-large; text-align: center;
    color: rgb(166, 166, 166)" >Hello, {{ user.get_username }}! Ready for a bad day? </p>

    <div id="01cards" class="row row-cols-1 row-cols-md-3 g-4">
        <!-- showing contents -->
    </div>

    <div style="text-align: center">
        <p></p>
        <a type="button" class="btn btn-primary" href="{% url 'todolist:add_activity' %}">Add Activity</a>        
        <!-- Modal Trigger Button -->
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Add Activity (alpha)
        </button>
        <a type="button" class="btn btn-danger" href="{% url 'todolist:logout' %}">Logout</a>
    </div> 
    
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Task</h1>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title">
                    </div>

                    <div class="mb-3">
                        <label class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description"></textarea>
                    </div>
                  </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="close"c>Close</button>
              <button type="submit" class="btn btn-primary" value="submit" data-bs-dismiss="modal" id="addtask">Add</button>
            </div>
          </div>
        </div>
      </div>


    <!-- AJAX function -->
    <script>
        function ajax_task(e) {
            e.preventDefault()
            const titleTask = $("#title").val()
            const descriptionTask = $("#description").val()

            const data = {
                title: titleTask,
                description: descriptionTask,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            }

            $.ajax({
                type: 'POST',
                url: "{% url 'todolist:add_activity' %}",
                data: data, 
                success: () => {
                    ajax_get()
                    $('.modal').hide();
                },
                dataType: 'json'
            });
        }


        function ajax_get() {
            $.get('/todolist/json', function (todolist) {
                $('#01cards').empty()
                todolist.map((task) => {
                    $('#01cards').append(
                        `
                        <div class="col">
                            <div class="card h-100">
                            <div class="card-body d-flex flex-column">
                                <h4 class="card-title">${task.fields.title} | ${task.fields.is_finished ? "beres!":"belum beres!"}</h4>
                                <h6 class="card-subtitle mb-2 text-muted">${task.fields.date}</h6>
                                <p class="card-text">${task.fields.description}</p>
                                <div class="flex justify-between gap-3">
                                <div class="flex flex-col justify-center rounded">
                                    <a type="button" class="btn btn-success" href="/todolist/status/${task.pk}">Check</a>
                                    <a type="button" class="btn btn-danger" href="/todolist/delete/${task.pk}">Delete</a>
                                </div>  
                                </div>
                            </div>
                            </div>
                        </div>
                        `
                    )
                })
            })
        }

        $(document).ready(function(){
            $("#addtask").click(ajax_task)
            $("#close").click(() => {
                $('.modal').hide();
            })
            ajax_get()
        });

    </script>

</body>


{% endblock content %}